### ISSUE TITLE
Incomplete generated data

### ISSUE THREAD

**Issue by clttyou** [centreborelli/HDR-DSP-SR#3]
![image](https://user-images.githubusercontent.com/39482181/202641766-3e6fe95d-9ccb-4fdc-a92c-9944a66b6cf5.png)
Hello, I have processed the data according to your requirements, but the generated data is incomplete. I hope to get your guidance
Here are the pictures I generated
![image](https://user-images.githubusercontent.com/39482181/202642007-8c9cad0d-2be2-4582-8b29-74941926fd4b.png)
![image](https://user-images.githubusercontent.com/39482181/202642064-d163b1b8-6f7f-41ee-8b08-67d92ac35d12.png)
![image](https://user-images.githubusercontent.com/39482181/202642136-7c6d5253-c5b0-4c52-bf94-27139a036fe4.png)

**Comment by ngoclongct** [comment]
Hi clttyou, thanks for your question. 
I don't remember why there is no "4" and "5" subfolders in the test set. Maybe I modified the pre-processing notebook somewhere. But actually that's not a big issue, you can debug this easily by modifying the test.py line 206 and 218 by "for i in range(6,16):" (modify 4 -> 6), the error will be fixed.

**Comment by clttyou** [comment]
> Hi clttyou, thanks for your question. I don't remember why there is no "4" and "5" subfolders in the test set. Maybe I modified the pre-processing notebook somewhere. But actually that's not a big issue, you can debug this easily by modifying the test.py line 206 and 218 by "for i in range(6,16):" (modify 4 -> 6), the error will be fixed.

Thank you very much for your answer. I have another question：
When I finish executing this line of code：python test.py .The generated results are shown in the following figure：
![image](https://user-images.githubusercontent.com/39482181/203534902-6cf68fb4-baba-4afe-b04d-204fa849b8f6.png)
![image](https://user-images.githubusercontent.com/39482181/203534940-9748370e-0cc7-4e56-b046-fc11b30a4161.png)

The generated results are in. npy format，Therefore, I want to know how to calculate the results of Table 4 in your paper？
![image](https://user-images.githubusercontent.com/39482181/203534548-f59a78ea-6447-440b-87b2-bc618e91413d.png)

**Comment by ngoclongct** [comment]
Hi, the super-resolution results you have here are the SR from real satellite data. Thus, there is no ground truth in this case, and we can't compute the PSNR score. 
In this paper, we generate the synthetic dataset (Table 4) from L1B data, but unfortunately, we don't have permission to publicly release the L1B data. If you want to compare with our method, you need to create your own synthetic dataset and then train our models on that dataset.

**Comment by clttyou** [comment]
> Hi, the super-resolution results you have here are the SR from real satellite data. Thus, there is no ground truth in this case, and we can't compute the PSNR score. In this paper, we generate the synthetic dataset (Table 4) from L1B data, but unfortunately, we don't have permission to publicly release the L1B data. If you want to compare with our method, you need to create your own synthetic dataset and then train our models on that dataset.

OK, thank you for your answer.
